spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.127.118:1521:orcl
    username: gyzdy2
    password: gyzdy21234
mybatis:
  mapper-locations: classpath:static/*Mapper.xml
  type-handlers-package: com.ml.typehandle
