spring:
  datasource:
    url: jdbc:mysql://192.168.127.118:3306/bendi?serverTimezone=CST
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:static/*Mapper.xml
